### ISSUE TITLE
Top and max level of headings not shown after reload

### ISSUE THREAD

**Issue by nheeren** [ssahara/dw-plugin-toctweak#4]
Hello!  TOCtweak is a really nice plugin. However, I have the issue that e.g. the setting `~~TOC:1-2~~` only works directly after i click the save button. When I reload the page, the command is ignored :(
Dokuwiki is Hrun and I put the command at the top of the page.

**Comment by ssahara** [comment]
Hi nheeren,
Thanks for your reporting and kind words. I confirmed that  `{{TOC:1-2}}` works but  `~~TOC:1-2~~` not work as expected. I will look over source files, hopefully in this weekend.
Satoshi

**Comment by ssahara** [comment]
bug found at handlePostProcess() in class action_plugin_toctweak_rendertoc.
Please test test branch https://github.com/ssahara/dw-plugin-toctweak/tree/patch
It will be merged to master in a few days.

**Comment by ssahara** [comment]
Hi @nheeren, I just ask you whether your issue has solved?

**Comment by nheeren** [comment]
Sorry I overlooked your previous reply. Yes it totally works. Thank you!!
What is the difference between {{}} and ~~~~ by the way?
